name: singularity-onboarding
channels:
  - conda-forge
dependencies:
  - python>=3.11
  - requests
  - pandas
  - ipywidgets
  - ipykernel
  - ipyaggrid
  - seaborn
  - ipympl
  - tzlocal
  - jupyterlab
  - nbconvert
