name: singularity-onboarding
channels:
  - conda-forge
dependencies:
  - python>=3.11
  - pip
  - pip:
    - requests
    - pandas
    - ipywidgets
    - ipykernel
    - ipyaggrid
    - seaborn
    - ipympl
    - tzloca
    - jupyterlab
    - nbconvert
